dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
language: csharp
solution: ZDragon.NET.sln
mono: none
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet build --configuration Release
  - dotnet test
before_deploy:
  - dotnet publish CLI -c Release --runtime win-x64 /p:PublishSingleFile=true
  - dotnet publish CLI -c Release --runtime osx-x64 /p:PublishSingleFile=true
deploy:
    provider: releases
    api_key: $ZDragon_GitHub_Token
    draft: true
    skip_cleanup: true
    name: $(git describe)
    on:
        tags: true
    file:
        - "CLI/bin/Release/netcoreapp3.0/win-x64/publish/CLI.exe"
        - "CLI/bin/Release/netcoreapp3.0/osx-x64/publish/CLI"