language: csharp
solution: ZDragon.NET.sln
mono: none
services:
  - docker

before_install:
  - docker pull mcr.microsoft.com/dotnet/core/sdk:3.1
  - docker run -it mcr.microsoft.com/dotnet/core/sdk:3.1

script:
  - ls

