language: csharp
solution: ZDragon.NET.sln
mono: none
services:
  - docker

before_install:
  - docker pull mcr.microsoft.com/dotnet/core/sdk:3.1
  - docker run -itv ./:/solution mcr.microsoft.com/dotnet/core/sdk:3.1 /bin/sh

script:
  - ls
  - cd /solution
  - ls
  - dotnet build --configuration Release
  - dotnet test