dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
language: csharp
solution: ZDragon.NET.sln
mono: none
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet build --configuration Release
  - dotnet test
before_deploy:
  - bash ./release.sh
  - NAME=$(git describe --tag --abbrev=0)
deploy:
    provider: releases
    api_key: $ZDragon_GitHub_Token
    draft: true
    skip_cleanup: true
    name: $NAME
    on:
        tags: true
    file: lib/*