language: csharp
solution: ZDragon.NET.sln
mono: none
services:
  - docker

before_install:
  - docker pull mcr.microsoft.com/dotnet/core/sdk:3.1

script:
  - docker run -d mcr.microsoft.com/dotnet/core/sdk:3.1 /bin/sh -c "dotnet build --configuration Release"
  - docker run -d mcr.microsoft.com/dotnet/core/sdk:3.1 /bin/sh -c "dotnet build --configuration Release"
