dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
language: csharp
solution: ZDragon.NET.sln
mono: none
script:
  - ls /home/travis/build/Baudin999/ZDragon.NET/CompilerTests
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version
  - dotnet build --configuration Release
