language: csharp
solution: ZDragon.NET.sln
mono: none
services:
  - docker

before_install:
  - docker pull mcr.microsoft.com/dotnet/core/sdk:3.1

script:
  - ls -la
  - docker run mcr.microsoft.com/dotnet/core/sdk:3.1 /bin/sh -c "ls"