language: csharp
solution: ZDragon.NET.sln
mono: none
services:
  - docker

before_install:
  - docker pull mcr.microsoft.com/dotnet/core/sdk:3.1

script:
  - docker run -iv $TRAVIS_BUILD_DIR:/solution mcr.microsoft.com/dotnet/core/sdk:3.1 /bin/sh -c "cd /solution && ./test.sh"
    