dist: xenial
addons:
  snaps:
    - name: dotnet-sdk
      classic: true
      channel: latest/beta
sudo: required
language: csharp
solution: ZDragon.NET.sln
mono: none
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet tool install --global coverlet.console
  - export PATH="$PATH:/home/travis/.dotnet/tools"
  - dotnet build --configuration Debug
  - coverlet ./CompilerTests/bin/Debug/netcoreapp3.0/CompilerTests.dll --target "dotnet" --targetargs "test --no-build"
